services:
  app:
    build:
      context: ../../
      dockerfile: infrastructure/app/Dockerfile
    container_name: mailinwhite-app
    ports:
      - '8081:8081'
    networks:
      - appnet

  nginx:
    image: nginx:1.27.2
    container_name: mailinwhite-nginx
    volumes:
      - ../../public:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - app
    networks:
      - appnet

  postfix:
    build:
      context: ../../
      dockerfile: infrastructure/postfix/Dockerfile
    container_name: mailinwhite-postfix
    ports:
       - '2025:25'
    networks:
      - appnet

  mailcatcher:
    image: jeanberu/mailcatcher:0.10.0
    container_name: mailinwhite-mailcatcher
    ports:
       - '8082:1080'
    networks:
      - appnet

  redis:
    image: redis:7.4.1-alpine
    container_name: mailinwhite-redis
    ports:
      - '6379:6379'
    volumes:
      - 'mailinwhite-data:/data'
    networks:
      - appnet
      
volumes:
  mailinwhite-data:
    driver: local

networks:
  appnet:
    driver: bridge
